name: Dependency Pull Request

on:
  pull_request:
    branches: [master]
    paths:
      - '**/package.json'
      - '!.yarn/**'
      - '!yarn.lock'
      - '!.pnp.js'

jobs:
  check-cache:
    name: Check Yarn Cache
    # See dependabot workflow
    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Check dependencies
        run: yarn --check-cache
      - uses: EndBug/add-and-commit@v7
        with:
          add: .yarn .pnp.js yarn.lock
          message: 'chore(package): update dependencies'
